//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseAccountingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.ProductArrival = new HashSet<ProductArrival>();
            this.ProductConsumption = new HashSet<ProductConsumption>();
        }
    
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public int INNId { get; set; }
        public int SNILSId { get; set; }
        public int PassportId { get; set; }
        public int PositionId { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime DateOfEntry { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int GenderId { get; set; }
        public int MaterialLiabilityId { get; set; }
        public int EmploymentHistoryId { get; set; }
        public string FullName => $"{Surname} {Name} {Patronymic}";

        public virtual EmploymentHistory EmploymentHistory { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual INN INN { get; set; }
        public virtual MaterialLiability MaterialLiability { get; set; }
        public virtual Passport Passport { get; set; }
        public virtual Position Position { get; set; }
        public virtual SNILS SNILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductArrival> ProductArrival { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductConsumption> ProductConsumption { get; set; }
    }
}
