//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseAccountingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductArrival = new HashSet<ProductArrival>();
            this.ProductConsumption = new HashSet<ProductConsumption>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ProductGroupId { get; set; }
        public int ProductClassId { get; set; }
        public int UnitId { get; set; }
        public string Manufacturer { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public System.DateTime ManufactureDate { get; set; }
        public double Quantity { get; set; }
        public string Description { get; set; }
    
        public virtual ProductClass ProductClass { get; set; }
        public virtual ProductGroup ProductGroup { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductArrival> ProductArrival { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductConsumption> ProductConsumption { get; set; }
    }
}
